TRIB-143: implements correct To Be Reviewed Checker Service (#93)
* TRIB-143: WIP troubleshooting ungroomed method
- Added @schedule to ToBeReviewedCheckerServiceImpl updateUngroomedPhrases
- Troubleshooting JSONnull error

* TRIB-143: refactors validate phrase to use save()
- removes call to ToBeReviewedRepository.setHasBeenGroomed
- uses toBeReviewed setter to setHasBeenGroomed
- uses save() to update record in ToBeReviewedRepository

* TRIB-143: removes setHasBeenGroomed from repo
- removes setHasBeenGroomed from ToBeReviewedRepository in favor of using implicit save()
- refactors ToBeReviewedCheckerServiceImplTest to check for ToBeReviewedRepository setHasBeenGroomed property (3 tests affected)

* TRIB-143: removes troubleshooting print statements

* TRIB-143: adds PartsOfSpeech enum class

* TRIB-143: integrated phrase service isPhraseValid
- used phrase service validator method to check if phrase has already
been rejected, if any word of the indicated type has been rejected,
and if verb or noun are null
- removed redundant code that also checked for this

* TRIB-143: refactors checkPartOfSpeech to skip null
- adds check for null parts of speech in results from word details

* TRIB-143 fixes test for no noun
- refactors validatePhraseComponentWhenCriticalComponentIsEmpty with to
use newly added phrase service validator

* TRIB-143: removes phrase service check
- the grooming service was checking the api and our rejected tables.
Checking our rejected tables is handled in the AttributesAPIController
call to our phrase service and is not needed here.

* TRIB-143: refactors checkPartOfSpeech for null
- returns true if words api parts of speech is null to ensure manual review
- refactors checkPartOfSpeech params. removes word details and adds call within method

* TRIB-143: WIP fix compilation error in test
- temporarily refactors test to allow program to run
- will refactor tests after all code changes complete

* TRIB-143: refactors validatePhrase with nullvalue
- adds check for nullvalue constant in noun and adverb
- skips checking words api for nullvalue words

* TRIB-143: updates logger to log
- updates all related validation log messages to use lombok log
- removes imports for other logger services

* TRIB-143: WIP troubleshooting update tables
- passing in a non-english word is causing error: org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing:

* TRIB-143: updated rejected phrase repository
- removed custom query in favor of using hibernate .save() method in the ToBeReviewedCheckerServiceImpl update tables method.

* TRIB-143: removes delete from Review Sub User Repo
- removes custom delete from ReviewSubmittingUserRepository in favor of using hibernate .delete()
- fixes ToBeReviewedCheckerServiceImplTest validatePhraseWhenPhraseValid to use delete
- fixes ToBeReviewedCheckerServiceImplTest updateTablesWhenPhraseInvalidAndNoMatchingRejectedPhrase to use delete and to assertEquals for user ignored
- updates ToBeReviewedCheckerServiceImplTest to extend AbstractServiceImplTest in order to use USER_ID

* TRIB-143: refactors ToBeRevCheckerImpl updateTable
- refactors deleting from the to be reviewed table statement to delete by ReviewSubmittingUser instead of just user ToBeReviewed Id

* TRIB-143: removes redundant log message
- get word details method will log if a word is not in the English language

* TRIB-143: fixes checkPartOfSpeech test
- changes return value to Optional.of(wordDetails)

* TRIB-143: fixes test for incorrect part of speech
- updates validatePhraseComponentWhenComponentIsIncorrectPartOfSpeech do return statement to return Optional.of(wordDetails)

* TRIB-143: fixes test for expected noun
- updates validatePhraseComponentWhenComponentIsValidNoun doreturn statement to return Optional.of(wordDetails)

* TRIB-143: removes unnecessary tests
- removes two tests for phrase validation. This logic was removed from ToBeReviewedCheckerServiceImpl because validation checking is handled in phrase service when the AttributesApiController endpoint applyPhraseToUser is called.

* TRIB-143: removed ToBeReviewedChecker
- per the ticket, this file was redundant and should be deleted

* TRIB-143: removed commented out code
- removed commented out code that was missed in previous refactoring

* TRIB-143: removed unused part of speech enum class
- This class was created during refactoring of ToBeReviewedCheckerService, but was never actually implemented

* TRIB-143: removes word api commented out code
- removes commented out declaration that is unnecessary

* TRIB-143: removes try/catch in validatePhraseComp
- Ealier refactoring removed this try catch in favor of using the try/catch in getWordDetails

* TRIB-143: changes scheduled task to 10 minutes
- This was set to 1 minute for development testing. Updated back to required 10 minutes.

* TRIB-143: adds TODO for Jira TRIB-153
- TODO: Create notification for users when their submitted phrase has been rejected after review

* TRIB-143: removes unnecessary import
- removes mistaken import for TODO package

* TRIB-143: adds check for missing results set
- addresses bug in Words API where some words, such as "bakes", do not have a "results" set defined. In such a case, checkPartOfSpeech logs a warning and returns "true" to ensure manual review.
- modifies try/catch log for missing parts of speech to match wording for missing result set bug.

* TRIB-143: updates part of speech error type
- updates the try/catch error type for a missing part of speech to be a null pointer exception

* TRIB-143: adds comment to null result set log msg

* TRIB-143: updated error type to correct type
- udpates missing part of speech try/catch error type to UnsupportedOperationException

* TRIB-143: adds log msg for wrong part of speech
- moves log functionality from validatePhraseComponent to checkPartOfSpeech

* TRIB-143: removes validatePhraseComponent method
- removes method from ToBeReviewedCheckerServiceImpl and updates previous calls to go to checkPartOfSpeech
- removes method from ToBeReviewedCheckerService
- updates calls in ToBeReviewedCheckerServiceImplTest to go to checkPartOfSpeech

* TRIB-143: updates part of speech log message

* TRIB-143: adds test for empty results set
- adds test for instance where Words API does not have a "results" set for the word
- updates ToBeReviewedCheckerServiceImplTest import for org.junit.jupiter.api.Assertions to use multiple types of assertions

* TRIB-143: adds test for missing part of speech
- adds test for known issue where some words may have a null part of speech

* TRIB-143: adjusts groomed phrase service to 10 min
- updates the time back to 10 minutes. It was set to one minute for testhing in dev.

* TRIB-143: removes redundant calls to words api
- saves call to words api in optional

* TRIB-143: removed uneccessary ID notation in repo
- removed @ID annotation for ReviewSubmittingUserRepository